bluerobotics/ping-viewer-next

- .gitignore
- Cargo.toml
- build.rs
- src/cli/manager.rs
- src/cli/mod.rs
- src/logger/manager.rs
- src/logger/mod.rs
- src/main.rs
- src/server/manager.rs
- src/server/mod.rs
Refs:
https://github.com/mavlink/mavlink-camera-manager
https://github.com/bluerobotics/navigator-web-assistant
https://github.com/rustyhorde/vergen
https://github.com/rustyhorde/vergen/blob/master/MIGRATING_v8_to_v9.md
https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html
Logs as /logs/ping-viewer.2024-05-30-19.log
*Sync with latest vergen 9.0 versions - through beta version with "gix flavour",
*Shows building dependencies:
*( Todo! A new filter with different levels for each dependency)  using vergen dependencies list - could be usefull for mavlink and mavlink2rest.
> Add: logger&cli&server modules

- Cargo.toml
- src/device/devices.rs
- src/device/manager.rs
- src/device/mod.rs
- src/main.rs
This PR adds DeviceManager and Device modules, each following the actor pattern.
Each structure has its own handler, allowing usage across multiple and different threads.
Device requests made to the Manager are forwarded directly to the respective Device. Each request provides a Result<Answer, ManagerError>.
Requires merge&bump on ping-rs: 
some cool refs:
https://ryhl.io/blog/actors-with-tokio/
https://theari.dev/blog/tokio-actors/
https://www.oreilly.com/library/view/applied-akka-patterns/9781491934876/ch01.html
https://www.amazon.com/Rust-Web-Programming-hands-applications/dp/1803234695
> Add: Device manager

- Cargo.toml
- src/device/manager.rs
- src/main.rs
- src/server/manager.rs
- src/server/mod.rs
- src/server/protocols/mod.rs
- src/server/protocols/v1/errors.rs
- src/server/protocols/v1/frontend/index.html
- src/server/protocols/v1/mod.rs
- src/server/protocols/v1/rest.rs
- src/server/protocols/v1/websocket.rs
> Add : Device manager integrations (RestAPI and Websocket)

- src/device/manager.rs
- src/device/manager/continuous_mode.rs
- src/device/manager/device_handle.rs
- src/device/manager/mod.rs
- src/device/mod.rs
- src/main.rs
**Add Data Broadcasting Focused on Ping1D and Ping360 Classes:**
**How it Works:**
```json
{
"EnableContinuousMode": "00000000-0000-0000-1cc4-7b702224f52d"
}
```
```json
{
"DisableContinuousMode": "00000000-0000-0000-1cc4-7b702224f52d"
}
```
By default, devices created will start in ContinuousMode, sending `DeviceData` or `PingProfile` over WebSocket, depending on the device type.
*The Ping360 will use the current values retrieved from `DeviceData`. This allows users to update the parameters as follows:
```
1. ContinuousMode should be disabled.
2. A transducer command should be sent.
3. ContinuousMode should be restarted.
```
**Other Upgrades Available in This PR:**
```
- Added helpers to keep the code maintainable and upgradeable to newer models.
- Added a broadcast startup routine for …
```
> Add: Enable/Disable Continuous_Mode for Ping1D & Ping360 through websocket

- src/cli/manager.rs
- src/device/manager/mod.rs
- src/main.rs
Needs:
Details:
```
pi@raspbian-armv7-kernel-5:~/deploy $ ./ping-viewer-next --log-current-crate-only --enable-auto-create
2024-08-01T19:58:37.269940Z  INFO main ThreadId(01) src/logger/manager.rs:94: ping-viewer-next, version: 0.0.0-17c4ed001ee17f263ef4cd5f50b9d13bead8f7b5, build date: 2024-08-01
2024-08-01T19:58:37.270141Z  INFO main ThreadId(01) src/logger/manager.rs:102: Build dependencies details: actix 0.13.5,actix-web 4.6.0,actix-web-actors 4.3.0,bluerobotics-ping 0.3.0,chrono 0.4.38,clap 4.5.4,lazy_static 1.4.0,mime_guess 2.0.5,paperclip 0.8.2,regex 1.10.5,rust-embed 8.5.0,serde 1.0.202,serde_json 1.0.117,thiserror 1.0.61,tokio 1.38.0,tokio-serial 5.4.4,tracing 0.1.40,tracing-appender 0.2.2-with-filename-suffix,tracing-log 0.2.0,tracing-subscriber 0.3.18,tracing-tracy …
```
> Add: AutoCreate method for DeviceManager

- src/device/manager/mod.rs
- src/main.rs
- src/server/protocols/v1/websocket.rs
> Update: Requests pattern

- .github/workflows/action.yml
Based on mavlink-server actions,
> Add: Build and deployment to gh-actions

- src/device/manager/device_discovery.rs
- src/device/manager/mod.rs
This PR adds network discovery and upgrade AutoCreate method on Device_Manager.
> Add: Add network discovery and upgrade AutoCreate

- src/device/devices.rs
Allow device actors to access common methods
> Add: Common methods for ping1d and ping360 device actors

- src/device/manager/mod.rs
json command:
```
{
"command": "ModifyDevice",
"module": "DeviceManager",
"payload": {
"modify": {
"Ip": "0.0.0.0"
},
"uuid": "00000000-0000-0000-e2b0-34ddc8816c48"
}
}
```
Modify ping360 IP adress
Needs:
> Add: ModifyDevice method and change ip option

- Cargo.toml
- src/logger/manager.rs
Still produces the same required output:
Allow the crate to publish modules/lib and share resources.
> Upgrade: Sync to use current tracing-append crate

- Cargo.toml
Newer versions of the Tracy crate run and start storing logs in RAM by default, causing memory consumption that is never freed since there are no clients.
This PR removes this behavior to ondemand, so logs are only generated after a client request; otherwise, they are not.
> Fix: OOM Error while runnning application.

- Cargo.toml
> ping-viewer-next-desktop: Embed frontend to dekstop App

- Cargo.toml
- src/device/manager/device_discovery.rs
- src/device/manager/mod.rs
set_baudrate_preroutine method was implemented to make sure that Ping devices successfully communicate at the selected baudrate;
serial_discovery method now iterates through various baudrate values and classify then;
autocreate process optimized and verified with ping1d, ping2, ping360 serial and udp. ( directly and over usb hub )
abnormal behavior found on ping2 answer to check quality, over 100ms ( tested with different ftdi/cables)
> Add: Auto_baudrate to device discovery process

- ping-viewer-next-frontend/src/App.vue
- ping-viewer-next-frontend/src/layouts/default.vue
- ping-viewer-next-frontend/src/pages/addons/widget/[type]/index.vue
- ping-viewer-next-frontend/src/pages/addons/widget/index.vue
- ping-viewer-next-frontend/src/router/index.js
- src/server/protocols/v1/rest.rs
Users now can use /addons/widget/[type] route.
Allowing to load components directly with:
```
http://localhost:3000/addons/widget/ping1d?uuid=00000000-0000-0000-e5f4-0ff43386986c
http://localhost:3000/addons/widget/ping1d?server=http://192.168.1.1:8080&uuid=00000000-0000-0000-e5f4-0ff43386986c
```
Two types available, `ping1d` and `ping360`.
Widget Ping360:
Widget Ping1D:
Short guide available on `addons/widget/` :
> Add: vue router forward components /addon/widget/

- ping-viewer-next-frontend/src/App.vue
- ping-viewer-next-frontend/src/components/widgets/sonar1d/Ping1D.vue
- ping-viewer-next-frontend/src/layouts/default.vue
- ping-viewer-next-frontend/src/plugins/vuetify.js
Allow Cockpit to load widgets using iframe.
> ping-viewer-next-frontend: Fix: remove background for widgets 

- .github/workflows/action.yml
- Cargo.toml
- src/device/manager/device_discovery.rs
- src/device/manager/mod.rs
Solves:
https://github.com/bluerobotics/ping-viewer-next/issues/74
`--features blueos-extension `
1. List available bridged ports from the ping service
2. Skip them when probing serial devices
3. Create a UDP device pointing to the ping-bridged one
Preview:
> Add: BlueOS Ping integration

- src/device/devices.rs
- src/device/manager/device_handle.rs
- src/device/manager/discovery_service.rs
- src/device/manager/mod.rs
Improve current device scanning process:
New status "Available" indicates devices are fully scanned/tested and added to device manager;
Service runs in background with 30s timer, skipping known Available device sources;
Device manager only upgrades devices using previous settings;
Auto_create only upgrades devices from Available to ContinuousMode/Running;
ContinuousMode executes auto_create if requested for "Available" devices;
tldr:
DeviceManager commands are faster due to using pre-tested settings(all creation, upgrade, baudrate process were moved to discovery service) ;
Devices dont need to lock/run a resource;
It will allow a better user experience to just double click desired device(next PR);
> Add: Discovery service

- blueos-ping-viewer-next/Dockerfile
- blueos-ping-viewer-next/files/entrypoint.sh
Fixed permission-related issues for serial devices already in use.
In this case, William observed malfunctions on GPS, which was receiving undesired probing from the serial discovery service.
Docker's default user has root permissions, so this approach creates a user with restricted permissions.
We also found some issues with `binding volumes ` when the user is different from `root`.
1. To solve the issue, we added a new user group for the Alpine container, `pingviewer`
2. Alpine needs a shadow package as it will allow calling su and changing to this new user at runtime (in the entrypoint.sh)
3. Volumes bind normally since they're mounted as root
4. We should document this somewhere (?)
Added logs and volume binding (/usr/blueos/extensions/ping-viewer-next/) following our standard …
> BlueOS: Improve serial permissions setup and bind logs folder

- blueos-ping-viewer-next/Dockerfile
- blueos-ping-viewer-next/README.md
BlueOS Extension updates:
- Corrects the invalid `type`
- Updates the README link to the one in the new repo
- Updates the version references to the _next_ patch
- Would be good if the state after merging this can be tagged as `1.0.0-beta.6`
- Updates the README to mention the Cockpit widget functionality
- Includes the BlueOS version requirement, per @vshie's request
> Mention cockpit widget in BlueOS Extension README

- src/device/manager/continuous_mode.rs
- src/device/manager/discovery_service.rs
- src/device/manager/mod.rs
Adds compability with new ping360 firmware,
For now, serial mode will still use the software continuous mode, 
Since it needs a smart way to deal with streams before send it to device creation ( it's missing commands such serial break or othe specific ones), for UDP we dont have this issue as we can send msgs from different threads without any problems.
The BlueOS experience takes advantage of continuous mode since it uses UDP bridged connection.
> Ping360 new firmware

- src/device/manager/discovery_service.rs
For BlueOS extension, ping-viewer-next will let ping service handle devices.
> Blueos discovery only udp
